name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
     tf_action:
        description: "Terraform action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: apply

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_VAR_ami_id: ${{ secrets.AMI_ID }}
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: generate variable.tfvars
      working-directory: terraform
      run: |
        cat <<EOF > terraform.tfvars
        ami   = "${{ secrets.TF_VAR_ami_id }}"
        key_name = "${{ secrets.TF_VAR_key_name }}"
        EOF

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform validate
      working-directory: terraform
      run: terraform validate
      
    - name: Terraform plan
      if: github.event.inputs.tf_action == 'plan'
      working-directory: terraform
      run: terraform plan

    - name: Terraform Apply
      if: github.event.inputs.tf_action == 'apply'
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: github.event.inputs.tf_action == 'destroy'
      working-directory: terraform
      run: terraform destroy -auto-approve

    - name: Capture Terraform Outputs
      if: github.event.inputs.tf_action == 'apply'
      working-directory: terraform
      run: |
          echo "APP_IP=$(terraform output -raw app_node_ip)" >> $GITHUB_ENV
          echo "BASTION_IP=$(terraform output -raw bastion_node_ip)" >> $GITHUB_ENV

    - name: Show Outputs
      if: github.event.inputs.tf_action == 'apply'
      run: |
             echo "App Node IP: ${{ env.APP_IP }}"
             echo "Bastion Node IP: ${{ env.BASTION_IP }}"
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/ec2.pem
        chmod 400 ~/.ssh/ec2.pem

